; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Scegli l'ambiente di default. Puoi cambiarlo dalla UI di VSCode.
default_envs = nano

[env]
; Opzioni comuni a tutti gli ambienti
framework = arduino
lib_deps =
    ; Aggiunge la dipendenza dalla libreria Adafruit NeoPixel
    adafruit/Adafruit NeoPixel @ ^1.12.0
monitor_speed = 9600

[env:nano]
; Configurazione specifica per Arduino Nano
platform = atmelavr
board = nanoatmega328
build_flags =
    ; Definisce il pin da usare per la striscia LED
    -D VU_METER_DATA_PIN_1=6

[env:nano_audio]
; Ambiente per Nano con input audio analogico (3 strisce)
platform = atmelavr
board = nanoatmega328
build_flags =
    -D INPUT_MODE_ANALOG
    -D ANALOG_INPUT_PIN=A0
    -D VU_METER_DATA_PIN_1=6
    -D VU_METER_DATA_PIN_2=7
    -D VU_METER_DATA_PIN_3=8

[env:esp32_rover]
; Configurazione specifica per ESP32-WROVER-KIT
platform = espressif32
board = esp-wrover-kit
build_flags =
    ; Definisce il pin da usare per la striscia LED
    -D VU_METER_DATA_PIN_1=23

[env:esp32_rover_audio]
; Ambiente per ESP32 con input audio analogico (3 strisce)
platform = espressif32
board = esp-wrover-kit
build_flags =
    -D INPUT_MODE_ANALOG
    -D ANALOG_INPUT_PIN=36 ; GPIO36 è ADC1_CH0
    -D VU_METER_DATA_PIN_1=23
    -D VU_METER_DATA_PIN_2=22
    -D VU_METER_DATA_PIN_3=21
